server:
  port: 8085
  error:
    include-message: always
    include-stacktrace: never

spring: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://host.docker.internal:49153/service-customer
    username: root
    password: mysqlpw
    driverClassName: com.mysql.jdbc.Driver
welcome:
  message: Welcome to customer service on Dev Environment
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    com:
      ioSoftware: debug
