#Application Configuration
server:
  port: 8093
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:49153/service-shopping
    username: root
    password: mysqlpw
    driverClassName: com.mysql.jdbc.Driver

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka
management:
  endpoints:
    web:
      exposure:        
        include: "*"
  endpoint:
    hystrix:
      stream:
        enabled: true
Feign:
  hystrix:
    enabled: true
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
